### ISSUE TITLE
Missing totp 

### ISSUE THREAD

**Issue by widarlein** [Eitraz/avanza-api#1]
Hi! I noticed that in contrast to https://github.com/fhqvst/avanza this lib does not handle the totp code generation from the totp secret. Is this by design and the user is supposed to handle the code generation or if, in your opinion, the lib would be enriched by including this?
Cheers!

**Comment by Eitraz** [comment]
Hi!

This is by design. I think the intention of totp secret is to be provided by the user. If a user of the library want that functionality it should be fairly easy to add when totp code is asked for.

Regards,
Petter
